# Generated by Django 6.0.5 on 2026-05-27 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY_PORTAL', 'Utility Portal'), ('TRAVEL_PLATFORM', 'Travel Platform')], max_length=50)),
                ('ingestion_method', models.CharField(default='CSV_UPLOAD', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_systems', to='tenants.tenant')),
            ],
        ),
    ]
