# Generated by Django 6.0.5 on 2026-05-27 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('sources', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('scope_category', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('quantity_original', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_original', models.CharField(blank=True, max_length=50)),
                ('quantity_normalized', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_normalized', models.CharField(blank=True, max_length=50)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('co2e', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], default='PENDING', max_length=20)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('is_locked', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.facility')),
                ('ingestion_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_activities', to='ingestion.ingestionbatch')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_activity', to='ingestion.rawrecord')),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_activities', to='sources.sourcesystem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_activities', to='tenants.tenant')),
            ],
        ),
    ]
